### ISSUE TITLE
Wrong require() argument on website

### ISSUE THREAD

**Issue by markolbert** [cfurst/CronJobManager#1]
The examples show require('crontab_manager') when it should actually be require('cron-job-manager').

**Comment by cfurst** [comment]
Thanks. Will publish new version.

**Comment by cfurst** [comment]
New version published.I believe you can see the update here:

https://www.npmjs.com/package/cron-job-manager

apologies for any confusion and for the delay in fixing this.

Thanks to @davidalee for submitting the correction.
