### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by internette** [cfurst/CronJobManager#10]
https://github.com/cfurst/CronJobManager/blob/2da6d36641f9d3e9118b32c281d9b897c82b9a22/lib/crontab_manager.js#L14

**Comment by cfurst** [comment]
GAK! Thanks! You want to submit a PR for that? :) Get some dev credit.. add yourself as a contributor.. looks good on your  resume etc.. 👍

**Comment by cfurst** [comment]
Sorry for the delay.. this was fixed
