### ISSUE TITLE
Update cron to 1.8.2

### ISSUE THREAD

**Issue by naglafar** [cfurst/CronJobManager#18]
Hi cfust

Thanks for creating this lib is really good!

I was wondering if you could update `cron` to the latest version as it uses `moment-timezone` instead of `time`.

`Time` is a pain as it uses gyp to install and is OS specific. Time & alpine linux / node 12 don't get on well. 

Your tests work fine with cron @ 1.8.2.

**Comment by cfurst** [comment]
Pr in review process.

**Comment by cfurst** [comment]
Looks like some other tests are failing.. will fix , review and publish.. Thank you!
