### ISSUE TITLE
Create TypeScript typings

### ISSUE THREAD

**Issue by afonsojramos** [cfurst/CronJobManager#25]
Greetings, do you think it is possible for you to create TypeScript typings for the package?

I can try and help if you need.

**Comment by cfurst** [comment]
yes, this is a good idea. I can probably get a `.d.ts` document probably in a separate @types repo

**Comment by cfurst** [comment]
Ok .. I created a `-types-CronJobManager` repo since that's all github would allow.. I'll see if I can get a `tsconfig.json` and a `CronJobManager.d.ts` file going..

**Comment by cfurst** [comment]
I renamed the repo `CronJobManager-types` I'll try and get it going as a TS project with types declaration.

**Comment by cfurst** [comment]
I decided to forego the separate repo and such since this is really only one type we're talking about. This is basic first draft. suggestions welcome. take a look at [this PR](https://github.com/cfurst/CronJobManager/pull/32) and leave comments as necessary. Thanks!

**Comment by cfurst** [comment]
Released as part of [2.2.0](https://github.com/cfurst/CronJobManager/releases/tag/2.2.0)
