### ISSUE TITLE
couldn't stop job

### ISSUE THREAD

**Issue by Merrick17** [cfurst/CronJobManager#27]
couldn't stop job: fr4PEEt2-6p9p3diQQdHfPV3C7Jp2JnNGGtTzPYc: TypeError: Cannot read property 'running' of undefined

**Comment by cfurst** [comment]
Can you leave some more details on how to reproduce this?

**Comment by Merrick17** [comment]
Hello , thanks for commenting , the conflict whas with the name , i generated the name using keys on another app , after investigating the source code of this pacakge a'd following exactly i found out that the "-" and special symbols caused un issue so i removed them and lowerCased all letters and it workd . 
I'll close the issue now , since it's resolved thank you

**Comment by cfurst** [comment]
Awesome! Glad it worked out!
