### ISSUE TITLE
listCrons() Returns String Instead of JSON Object

### ISSUE THREAD

**Issue by EmirBoyaci** [cfurst/CronJobManager#28]
Hello @cfurst ,

I've just checked your package and installed. When I tried to use listCrons() method, it returns String. In case I need to get JSON object I parsed and used cron key and status. Could you please change listCrons() method returns JSON object? I also tried to JSON.parse() method but you implemented with single quotes so that JSON library cannot parse. Actually, there is no single quotes in JSON objects. The JSON standard requires double quotes and will not accept single quotes. I found my own path to parse. If you would like to know it's below.

Thanks.

```javascript
  listCrons() {
    const cronList = [];
    const crons = this.cronManager
      .listCrons()
      .substring(1, this.cronManager.listCrons().length - 1)
      .split("\n");
    for (let i = 0; i < crons.length; i++) {
      if (i !== 0 && i !== crons.length - 1 && crons[i].length > 0) {
        const secondSingleQuoteIndex = crons[i].indexOf("'", 1);
        const statusIndex = crons[i].search("status");
        cronList.push({
          key: crons[i].substring(1, secondSingleQuoteIndex),
          status: crons[i].substring(statusIndex + 8, crons[i].length - 1),
        });
      }
    }
    return cronList;
  }

**Comment by cfurst** [comment]
This is working as intended. It is meant to be used as a debugging tool to produce strings. If you want a JSON object, create a new method to produce a JSON object. I would be more than happy to review the PR.

Thanks.
