### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by FernandoGambaro** [cfurst/CronJobManager#29]
Hi, I got this error while trying your example

I got the current jobs:  CrontabManager {
  jobs: {
    this_job: <ref *1> CronJob {
      context: [Circular *1],
      _callbacks: [Array],
      onComplete: [Function: onComplete],
      cronTime: [Object],
      unrefTimeout: undefined,
      running: true,
      _timeout: Timeout {
        _idleTimeout: 2444325,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 689,
        _onTimeout: [Function: callbackWrapper],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: true,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 43,
        [Symbol(triggerId)]: 0
      }
    }
  }
}
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Timeout'
    |     property '_idlePrev' -> object with constructor 'TimersList'
    --- property '_idleNext' closes the circle
    at JSON.stringify (<anonymous>)

Any sugestions?

**Comment by cfurst** [comment]
Interesting... Can I see the code that is generating this error? It looks like it might be something  with one of the underlying libs.

**Comment by FernandoGambaro** [comment]
That happened to me when I was trying to return the details of the tasks to a jquery post request.

I solved it in the following way, where I only show the data that interests me.

tareas[i] = { jobs : Object.entries(manager.jobs)[i][0],
                    cronTime : Object.entries(manager.jobs)[i][1].cronTime.source,
                    zone : Object.entries(manager.jobs)[i][1].cronTime.zone, 
                    ejecuta : Object.entries(manager.jobs)[i][1]._callbacks
                };
