### ISSUE TITLE
Doesn't have cron date time jobs

### ISSUE THREAD

**Issue by jtwebman** [cfurst/CronJobManager#3]
Node-cron you can pass a datetime into it as well as a cron string. Shouldn't this library include that?

**Comment by cfurst** [comment]
Yes, that's true, cron does accept date objects for one time executions.. didn't add that in for this first round of versions. Please feel free to submit a Pull Request for such a thing.

**Comment by cfurst** [comment]
We have a pull request for this, unfortunately I'm not ready to commit to ECMA 6. I asked the author to resubmit using ECMA 5 with no response as yet , I think

**Comment by cfurst** [comment]
We are no longer running on any nodejs platform that only interprets ECMA 5 This is issue is fixed in PR 6, Version 2.0.0 unreleased as of yet.
