### ISSUE TITLE
cannot add dynamically taskFunction

### ISSUE THREAD

**Issue by FernandoGambaro** [cfurst/CronJobManager#30]
Hi, im trying to dynamically setup task, but I cannot specify function parameters, any suggestions?

**let ejecutar = 'EnviarMsgProgramado('+line+', '+destinatarios+')';**
manager.add( // this creates a new manager and adds the arguments as a new job.
            line,
            '* 0 19 * * 2', // the crontab schedule
            () => { **ejecutar** },
            {
                start:true,
                timeZone:"America/Montevideo",
                onComplete: () => { console.log("complete"); }
            });
        }

**Comment by cfurst** [comment]
I would use [bind](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind) and then access your arguments using `this`. Although that might not be what you are looking for.

Maybe if you gave me some details on what you are trying to achieve, I can be of more help.

**Comment by FernandoGambaro** [comment]
Of course, I have an array with tasks and for those tasks I execute a procedure that receives as parameters the name of the task and the key of the array

let destinatarios = 0;
 let tasks = ['Tarea1', 'Tarea2', 'Tarea3'];
    tasks.forEach(function(line){
       let ejecutar = 'EnviarMsgProgramado('+line+', '+destinatarios+')';
       manager.add( // this creates a new manager and adds the arguments as a new job.
       line,
       '* 0 19 * * 2', // the crontab schedule
       () => { ejecutar },
       {
           start:true,
           timeZone:"America/Montevideo",
           onComplete: () => { console.log("complete"); }
       });
    x++;
  }

**Comment by cfurst** [comment]
So it looks like bind might work for you. Basically you would have something like this:
```javascript
const jobFuncWrapper = function() {
   this.ejecutar // this gets set dynamically with each bind.
}
tasks.forEach((line) => {
    let ejecutar =  'EnviarMsgProgramado('+line+', '+destinatarios+')';
    manager.add( // this creates a new manager and adds the arguments as a new job.
        line,
       '* 0 19 * * 2', // the crontab schedule
        jobFuncWrapper.bind({ejecutar: ejecutar}), //bind ejecutar to jobFuncWrapper as 'this'
        {
          start:true,
          timeZone:"America/Montevideo",
          onComplete: () => { console.log("complete"); }
        });
}
```
`ejecutar`, if I'm understanding correctly, could be a function that gets wrapped, called and even have arguments passed to it if you also bind those arguments as different keys in the `this` object. If you bind the function with a named object, you can even change the `this` object on the fly (which is why binding functions can be a little bit dangerous):
```javascript
const jobWrapperFunction = function(){
    console.log(this.anArgument)
}
let myNewThis = {
    anArgument: "he said, she said"
}
let wrapperBound = jobWrapperFunction.bind(myNewThis)
wrapperBound() // he said, she said
myNewThis.anArgument = "No! she said, he said"
wrapperBound() // No! she said, he said
```
HTH!!

**Comment by FernandoGambaro** [comment]
Hi, I try this but cant get it work, finaly I just define one by one asignemet

Thank you very much
