### ISSUE TITLE
Cannot find package 'cron-job-manager'

### ISSUE THREAD

**Issue by FernandoGambaro** [cfurst/CronJobManager#31]
Thanks for sharing your knowledge, I have programmed an application with it, but when changing equipment and installing it, when trying to use it, it shows me the following error

Cannot find package 'cron-job-manager'

I have tried uninstalling and reinstalling it but I get the same result

To load it I use ES6
import CronJobManager from "cron-job-manager";
On the previous pc it works without problem, using ES6

Any idea?
Thnaks

**Comment by FernandoGambaro** [comment]
Hello again, I found a solution, the problem is in the npm path, after installing cron-job-manajer, you have to run npm link cron-job-manager

**Comment by cfurst** [comment]
That's new. Never had to do that before. I wonder if newer versions of npm are causing these issues.. I'll see if there is a fix on this end if I can reproduce.

Glad you were able to figure it out.

Carl.
