### ISSUE TITLE
[TS] Can't create an empty CronJobManager

### ISSUE THREAD

**Issue by Maxime-p** [cfurst/CronJobManager#39]
The doc say "_Just create one to add jobs to later_" by doing a `manager2 = new CronJobManager();`

But the constructor type require `key`, `tab` and `task`
![image](https://user-images.githubusercontent.com/43859895/178364681-911d348a-063b-43e3-b41d-ac23edae8d92.png)

Can we create a CronJobManager with no arguments ?

**Comment by cfurst** [comment]
To answer the question, technically, yes you can. However, with the current declaration, I think `tsc` will not allow you to transpile this to JS

**Comment by cfurst** [comment]
fix in PR #40

**Comment by cfurst** [comment]
fix merged to master will release in 2.3.1
