### ISSUE TITLE
Unknown timezone error 

### ISSUE THREAD

**Issue by devarajc** [cfurst/CronJobManager#4]
I'm getting this error when running the cron job manager.

couldn't start job: test001 Error:                                                                                                                                                              Unknown Timezone: 'America'

But I gave timezone as asia/kolkata

**Comment by cfurst** [comment]
Could you provide some code plz? Let me see how you are creating the job.
I think these things are case sensitive, so you might want to use 
Asia/Kolkata instead. Also, as a note, timezone issues are not something we support as they are probably issues with node-cron or time.c which are different projects, but I'll need to look at some code to determine if that is the case.

**Comment by cfurst** [comment]
Closing for age.
