### ISSUE TITLE
Is there a way for cron to invoke functions which take parameters?

### ISSUE THREAD

**Issue by kulkarnih** [cfurst/CronJobManager#5]
```
var options = {
    'param' : 'Hello World'
};
manager.add('next_job', '0 40 * * * *', function(options) {
console.log(options.param)
}, options);
```

Right now, I'm getting around this by using function closures.

**Comment by cfurst** [comment]
You should look at the docs for [Node Cron](https://github.com/ncb000gt/node-cron/blob/master/README.md). There is a way to add a context hash in the options hash. This context hash becomes _this_ in your function.
Something like this:

``` javascript
manager.add('next_job', '0 40 * * * *', function(options) {
console.log(this.param)
},{context: options});
```

Let me know of any issues.

Thanks.

**Comment by kulkarnih** [comment]
Thank you!

I'll close this issue.
