### ISSUE TITLE
Error while deleting and stop job

### ISSUE THREAD

**Issue by DaniyalGeek** [cfurst/CronJobManager#7]
`error in trying to stop job: a: TypeError: Cannot read property 'stop' of undefined`

i am deleting the job with defined key but i got this error

manager.deleteJob("a");

**Comment by cfurst** [comment]
It means that job "a" doesn't exist. You probably accidentally delete it elsewhere in your code, Maybe in a callback that got executed before this line did. Is there a stacktrace? 

I'll see if I can add in some better error handling tho. That message doesn't help. A stack trace would help pinpoint where this error is bubbling up.

Thanks,
C.

**Comment by cfurst** [comment]
closing for age.
