### ISSUE TITLE
You specified a Timezone but have not included the `time` module.

### ISSUE THREAD

**Issue by sagardalal21** [cfurst/CronJobManager#8]
**Error**:`Timezone functionality is disabled. Please install the `time` module to use Timezones in your application.`
Getting an error for this code:
```
var CronJobManager = require('cron-job-manager');

manager = new CronJobManager(
'job',
'*/30 * * * * *',
function () {

},
{
    start: false,
    timeZone: "Asia/Kolkata",
    completion: function () { console.log("job has stopped....") }
}
);
var index = 0;
var users = ['U1', 'U2', 'U3', 'U4']
manager.add('job1', '*/4 * * * * *', function () {
    var user = users[index];
    console.log("Sent To :" + user);
    index++;
    if (users.length == index) {
        manager.stop('job1');
    }
});
```

**Comment by internette** [comment]
Has this been resolved? I'm currently getting this error as well @cfurst

**Comment by sagardalal21** [comment]
@twaffl3s try installing time package to your application.
npm install time

**Comment by cfurst** [comment]
@sagardalal21 is right, you will need to have the most updated regions installed. You also might want to install moment-tz which will also pull that in.

**Comment by cfurst** [comment]
Did taking the steps above resolve your issue? @sagardalal21 @internette

**Comment by klemensz** [comment]
One note: If you have previously installed the 'time' module but upgraded to a newer node.js version in the meantime, you might have to re-install 'time'. The 'cron' module is silently swallowing this issues and doesn't print an error.
