### ISSUE TITLE
How do i run scheduler every 12 Hours ?

### ISSUE THREAD

**Issue by sagardalal21** [cfurst/CronJobManager#9]
Currently I am using below code to run it every 12 hours 

```
var CronJobManager = require('cron-job-manager');
var manager = new CronJobManager();
manager.add('job123', '0 */12 * * *', function () { 
	console.log('tick1...');
});
manager.start('job123');
```

**Comment by cfurst** [comment]
this package uses npm's cron library you can see documentation for crontab expressions:

https://www.npmjs.com/package/cron
basically you are setting it for every 12 minutes on the 12th minute.. so it should run  on the 12, 24, 36 minute of every hour..

to set every 12 hours I think this should work
`0 0 */12 * * *`

for it's seconds, minutes, hours, days of the month, months of the year and days of the week, which is not standard, for they added a `seconds` field for more precision. Check the cron lib link above for further details.
